import { BankRecFailure } from '../models/bank-reconciliation.models';

/**
 * Refusals of a statement intake — the import wizard and the manual statement
 * form share them (SPEC-manual-bank-reconciliation §4.10). Literal so the
 * i18n check sees every key.
 */
const STATEMENT_ERROR_KEYS: Readonly<Record<string, string>> = {
  IMPORT_FILE_ALREADY_COMMITTED: 'ACCOUNTING.BANK_IMPORT.ERROR.IMPORT_FILE_ALREADY_COMMITTED',
  STATEMENT_IMPORT_FAILED: 'ACCOUNTING.BANK_IMPORT.ERROR.STATEMENT_IMPORT_FAILED',
  STATEMENT_PERIOD_OVERLAP: 'ACCOUNTING.BANK_IMPORT.ERROR.STATEMENT_PERIOD_OVERLAP',
  STATEMENT_NOT_CONTIGUOUS: 'ACCOUNTING.BANK_IMPORT.ERROR.STATEMENT_NOT_CONTIGUOUS',
  STATEMENT_GAP_ACKNOWLEDGEMENT_NOT_APPLICABLE: 'ACCOUNTING.BANK_IMPORT.ERROR.GAP_ACKNOWLEDGEMENT_NOT_APPLICABLE',
  STATEMENT_TRANSACTION_OUT_OF_WINDOW: 'ACCOUNTING.BANK_IMPORT.ERROR.TRANSACTION_OUT_OF_WINDOW',
  CURRENCY_NOT_SUPPORTED: 'ACCOUNTING.BANK_IMPORT.ERROR.CURRENCY_NOT_SUPPORTED',
  IMPORT_NOT_COMMITTABLE: 'ACCOUNTING.BANK_IMPORT.ERROR.IMPORT_NOT_COMMITTABLE',
  IMPORT_ALREADY_COMMITTED: 'ACCOUNTING.BANK_IMPORT.ERROR.IMPORT_ALREADY_COMMITTED',
  IMPORT_DISCARDED: 'ACCOUNTING.BANK_IMPORT.ERROR.IMPORT_DISCARDED',
  STATEMENT_ALREADY_IMPORTED: 'ACCOUNTING.BANK_IMPORT.ERROR.STATEMENT_ALREADY_IMPORTED',
  ACCOUNT_NOT_RECONCILABLE: 'ACCOUNTING.BANK_IMPORT.ERROR.ACCOUNT_NOT_RECONCILABLE',
  JUSTIFICATION_REQUIRED: 'ACCOUNTING.BANK_IMPORT.ERROR.JUSTIFICATION_REQUIRED',
  STATEMENT_SUPERSESSION_NOT_ELIGIBLE: 'ACCOUNTING.BANK_IMPORT.ERROR.SUPERSESSION_NOT_ELIGIBLE',
  RECONCILIATION_WINDOW_ALREADY_RECONCILED: 'ACCOUNTING.BANK_IMPORT.ERROR.WINDOW_ALREADY_RECONCILED',
  AMOUNT_PRECISION_EXCEEDS_CURRENCY: 'ACCOUNTING.BANK_IMPORT.ERROR.AMOUNT_PRECISION_EXCEEDS_CURRENCY',
  OPTIMISTIC_LOCK: 'ACCOUNTING.BANK_IMPORT.ERROR.OPTIMISTIC_LOCK',
};

/** The message key for a refused statement write; an unknown code falls back to its HTTP status. */
export function statementFailureKey(failure: BankRecFailure): string {
  if (failure.code && STATEMENT_ERROR_KEYS[failure.code]) return STATEMENT_ERROR_KEYS[failure.code];
  switch (failure.status) {
    case 400:
      return 'ACCOUNTING.BANK_IMPORT.ERROR.INVALID';
    case 403:
      return 'ACCOUNTING.BANK_IMPORT.ERROR.FORBIDDEN_WRITE';
    default:
      return 'ACCOUNTING.BANK_IMPORT.ERROR.OTHER';
  }
}
