// GENERATED — do not edit by hand.
// Source: src/app/app.routes.ts + feature *.routes.ts (parsed by scripts/sitemap/extract-routes.mjs)
// Regenerate: npm run sitemap:routes:generate
//
// Every reachable route under the authenticated /app shell, with derived label,
// dynamic-param flag, and required roles/permissions. Consumed by the sitemap page.
import type { SiteMapMountEntry, SiteMapRouteEntry } from './models/site-map-section.model';

export const SITE_MAP_ROUTES: readonly SiteMapRouteEntry[] = [
  { route: '/app', label: "", dynamic: false },
  { route: '/app/accounting', label: "", dynamic: false },
  { route: '/app/accounting/credit-memos', label: "Credit Memos", dynamic: false, permissions: ['accounting:credit-memo:read'] },
  { route: '/app/accounting/credit-memos/:memoId', label: "Credit Memos", dynamic: true, permissions: ['accounting:credit-memo:read'] },
  { route: '/app/accounting/credit-memos/new', label: "New", dynamic: false, permissions: ['accounting:credit-memo:create'] },
  { route: '/app/accounting/events', label: "Events", dynamic: false, permissions: ['accounting:events:view'] },
  { route: '/app/accounting/events/:eventId', label: "Events", dynamic: true, permissions: ['accounting:events:view'] },
  { route: '/app/accounting/events/contract', label: "Contract", dynamic: false, permissions: ['accounting:events:view'] },
  { route: '/app/accounting/events/submit', label: "Event Submission", dynamic: false, permissions: ['accounting:events:submit'] },
  { route: '/app/accounting/invoices/:invoiceId/payment-status', label: "Payment Status", dynamic: true, permissions: ['accounting:ap:view'] },
  { route: '/app/accounting/payables/vendor-invoices', label: "Vendor Invoices", dynamic: false, permissions: ['accounting:analytics:view'] },
  { route: '/app/accounting/payables/vendor-invoices/:billId', label: "Vendor Invoices", dynamic: true, permissions: ['accounting:ap:view'] },
  { route: '/app/accounting/payables/vendor-invoices/exceptions', label: "Exceptions", dynamic: false, permissions: ['accounting:analytics:view'] },
  { route: '/app/accounting/payments/apply', label: "Apply", dynamic: false, permissions: ['accounting:payment:apply'] },
  { route: '/app/accounting/posting-rules', label: "Posting Rules", dynamic: false, permissions: ['accounting:posting_rules:view'] },
  { route: '/app/accounting/posting-rules/:ruleSetId', label: "Posting Rules", dynamic: true, permissions: ['accounting:posting_rules:view'] },
  { route: '/app/accounting/reports/labor-overhead', label: "Labor Overhead", dynamic: false, permissions: ['reporting:view:financial-statements'] },
  { route: '/app/accounting/vendor-payments', label: "Vendor Payments", dynamic: false, permissions: ['accounting:ap:view'] },
  { route: '/app/accounting/vendor-payments/:paymentId', label: "Vendor Payments", dynamic: true, permissions: ['accounting:ap:view'] },
  { route: '/app/accounting/vendor-payments/new', label: "New", dynamic: false, permissions: ['accounting:ap:pay'] },
  { route: '/app/admin', label: "", dynamic: false, roles: ['ROLE_ADMIN'] },
  { route: '/app/billing', label: "", dynamic: false },
  { route: '/app/billing/invoices/:invoiceId', label: "Invoices", dynamic: true, permissions: ['invoice:invoice:view'] },
  { route: '/app/billing/invoices/:invoiceId/payment-capture', label: "Payment Capture", dynamic: true },
  { route: '/app/billing/invoices/:invoiceId/payments/:paymentId/void-refund', label: "Void Refund", dynamic: true },
  { route: '/app/billing/invoices/:invoiceId/receipts', label: "Receipts", dynamic: true },
  { route: '/app/billing/invoices/:invoiceId/receipts/:receiptId', label: "Receipts", dynamic: true },
  { route: '/app/bulk-import/jobs', label: "Jobs", dynamic: false, permissions: ['bulkImport:status:read'] },
  { route: '/app/bulk-import/jobs/:jobId', label: "Jobs", dynamic: true, permissions: ['bulkImport:status:read'] },
  { route: '/app/crm', label: "", dynamic: false },
  { route: '/app/crm/bulk-import/customer', label: "Customer", dynamic: false, permissions: ['bulkImport:upload:execute'] },
  { route: '/app/crm/bulk-import/vehicle-fitment', label: "Vehicle Fitment", dynamic: false, permissions: ['bulkImport:upload:execute'] },
  { route: '/app/crm/bulk-import/vehicle-inventory', label: "Vehicle Inventory", dynamic: false, permissions: ['bulkImport:upload:execute'] },
  { route: '/app/crm/create-commercial-account', label: "Create Commercial Account", dynamic: false, permissions: ['crm:party:create'] },
  { route: '/app/crm/create-individual-person', label: "Create Individual Person", dynamic: false, permissions: ['crm:person:create'] },
  { route: '/app/crm/crm-snapshot/:partyId', label: "Crm Snapshot", dynamic: true, permissions: ['crm:party:view'] },
  { route: '/app/crm/customers', label: "Customers", dynamic: false, permissions: ['crm:party:view'] },
  { route: '/app/crm/integration/events', label: "Events", dynamic: false, permissions: ['accounting:events:view'] },
  { route: '/app/crm/merge-parties', label: "Merge Parties", dynamic: false, permissions: ['crm:party:merge'] },
  { route: '/app/crm/party/:partyId', label: "Party", dynamic: true, permissions: ['crm:party:view'] },
  { route: '/app/crm/party/:partyId/add-vehicle', label: "Add Vehicle", dynamic: true, permissions: ['vehicle-inventory:registry:create'] },
  { route: '/app/crm/party/:partyId/billing-rules', label: "Billing Rules", dynamic: true, permissions: ['crm:party:view'] },
  { route: '/app/crm/party/:partyId/contacts', label: "Contacts", dynamic: true, permissions: ['crm:relationship:read'] },
  { route: '/app/crm/snapshot', label: "Snapshot", dynamic: false, permissions: ['crm:party:view'] },
  { route: '/app/inventory', label: "", dynamic: false },
  { route: '/app/inventory/availability', label: "Availability", dynamic: false, permissions: ['inventory:availability:read'] },
  { route: '/app/inventory/bulk-import/stock', label: "Stock", dynamic: false, permissions: ['bulkImport:upload:execute'] },
  { route: '/app/inventory/by-location', label: "By Location", dynamic: false, permissions: ['inventory:on_hand:view'] },
  { route: '/app/inventory/by-location/:locationId', label: "By Location", dynamic: true, permissions: ['inventory:on_hand:view'] },
  { route: '/app/inventory/by-location/site/:siteId', label: "Site", dynamic: true, permissions: ['inventory:on_hand:view'] },
  { route: '/app/inventory/counts/adjustments', label: "Adjustments", dynamic: false, permissions: ['inventory:adjustment:view', 'inventory:adjustment:approve'] },
  { route: '/app/inventory/counts/execute', label: "Execute", dynamic: false, permissions: ['inventory:cycle_count:view'] },
  { route: '/app/inventory/counts/plans', label: "Plans", dynamic: false, permissions: ['inventory:cycle_count:view'] },
  { route: '/app/inventory/counts/plans/new', label: "New", dynamic: false, permissions: ['inventory:cycle_count:initiate'] },
  { route: '/app/inventory/fulfillment/workorders/:workorderId/consume-items', label: "Consume Items", dynamic: true, permissions: ['inventory:pick_list:view'] },
  { route: '/app/inventory/fulfillment/workorders/:workorderId/pick-execute', label: "Pick Execute", dynamic: true, permissions: ['inventory:pick_list:view'] },
  { route: '/app/inventory/fulfillment/workorders/:workorderId/pick-list', label: "Pick List", dynamic: true, permissions: ['inventory:pick_list:view'] },
  { route: '/app/inventory/fulfillment/workorders/:workorderId/return-to-stock', label: "Return To Stock", dynamic: true, permissions: ['inventory:return:view'] },
  { route: '/app/inventory/fulfillment/workorders/:workorderId/shortage-resolution', label: "Shortage Resolution", dynamic: true, permissions: ['inventory:shortage:view'] },
  { route: '/app/inventory/ledger', label: "Ledger", dynamic: false, permissions: ['inventory:ledger:view'] },
  { route: '/app/inventory/ledger/:ledgerEntryId', label: "Ledger", dynamic: true, permissions: ['inventory:ledger:view'] },
  { route: '/app/inventory/purchase-orders', label: "Purchase Orders", dynamic: false, permissions: ['order:purchase_order:view'] },
  { route: '/app/inventory/purchase-orders/:poId', label: "Purchase Orders", dynamic: true, permissions: ['order:purchase_order:view'] },
  { route: '/app/inventory/purchase-orders/:poId/edit', label: "Edit", dynamic: true, permissions: ['order:purchase_order:create'] },
  { route: '/app/inventory/purchase-orders/new', label: "New", dynamic: false, permissions: ['order:purchase_order:create'] },
  { route: '/app/inventory/putaway/tasks', label: "Tasks", dynamic: false, permissions: ['inventory:putaway:view'] },
  { route: '/app/inventory/putaway/tasks/:taskId', label: "Tasks", dynamic: true, permissions: ['inventory:putaway:view'] },
  { route: '/app/inventory/receiving/cross-dock', label: "Cross Dock", dynamic: false, allPermissions: ['inventory:receiving:complete', 'inventory:issue:parts'] },
  { route: '/app/inventory/receiving/receive-into-staging', label: "Receive Into Staging", dynamic: false, permissions: ['inventory:receiving:view'] },
  { route: '/app/inventory/replenishment/tasks', label: "Tasks", dynamic: false, permissions: ['inventory:on_hand:view'] },
  { route: '/app/inventory/security/permissions', label: "Permissions", dynamic: false, permissions: ['security:permission:view'] },
  { route: '/app/location', label: "", dynamic: false },
  { route: '/app/location/bays', label: "Bays", dynamic: false, permissions: ['location:bay:read'] },
  { route: '/app/location/bulk-import/location', label: "Location", dynamic: false, permissions: ['bulkImport:upload:execute'] },
  { route: '/app/location/location-sync', label: "Location Sync", dynamic: false, permissions: ['inventory:location:view'] },
  { route: '/app/location/locations', label: "Locations", dynamic: false, permissions: ['location:read'] },
  { route: '/app/location/locations/:id', label: "Locations", dynamic: true, permissions: ['location:read'] },
  { route: '/app/location/locations/:locationId/defaults', label: "Defaults", dynamic: true, permissions: ['location:read'] },
  { route: '/app/location/locations/new', label: "New", dynamic: false, permissions: ['location:write'] },
  { route: '/app/location/mobile-units', label: "Mobile Units", dynamic: false, permissions: ['location:mobile-unit:read'] },
  { route: '/app/location/storage-locations', label: "Storage Locations", dynamic: false, permissions: ['location:read'] },
  { route: '/app/order/:orderId/cancel', label: "Cancel", dynamic: true, permissions: ['order:order:cancel'] },
  { route: '/app/order/:orderId/price-override/:lineId', label: "Price Override", dynamic: true, permissions: ['order:price_override:view'] },
  { route: '/app/order/cart', label: "Cart", dynamic: false, permissions: ['order:order:create'] },
  { route: '/app/order/cart/:orderId', label: "Cart", dynamic: true, permissions: ['order:order:view'] },
  { route: '/app/people', label: "", dynamic: false },
  { route: '/app/people/bulk-import/people', label: "People", dynamic: false, permissions: ['bulkImport:upload:execute'] },
  { route: '/app/people/directory', label: "Directory", dynamic: false, permissions: ['people-contact:person:view'] },
  { route: '/app/people/employees/:id', label: "Employees", dynamic: true, permissions: ['people:employee_pii:view'] },
  { route: '/app/people/employees/:id/offboard', label: "Offboard", dynamic: true, permissions: ['people:employee:deactivate'] },
  { route: '/app/people/employees/new', label: "New", dynamic: false, permissions: ['people:employee:create'] },
  { route: '/app/people/identity-compliance', label: "Identity Compliance", dynamic: false, permissions: ['people:compliance:view'] },
  { route: '/app/people/person/:personId/locations', label: "Locations", dynamic: true, permissions: ['people:employee:view'] },
  { route: '/app/people/rbac/:personUuid', label: "Rbac", dynamic: true, permissions: ['people-contact:role:view'] },
  { route: '/app/people/timekeeping/approval', label: "Approval", dynamic: false, permissions: ['people:timekeeping:view'] },
  { route: '/app/people/timekeeping/discrepancy', label: "Discrepancy", dynamic: false, permissions: ['accounting:time:export'] },
  { route: '/app/people/timekeeping/export', label: "Export", dynamic: false, permissions: ['accounting:export:view'] },
  { route: '/app/people/timekeeping/work-session', label: "Work Session", dynamic: false },
  { route: '/app/people/timekeeping/work-session/:sessionId/submit', label: "Submit", dynamic: true },
  { route: '/app/platform/tenants', label: "Tenants", dynamic: false, roles: ['ROLE_PLATFORM_ADMIN'], permissions: ['platform:tenant:read'] },
  { route: '/app/platform/tenants/:id', label: "Tenants", dynamic: true, roles: ['ROLE_PLATFORM_ADMIN'], permissions: ['platform:tenant:read'] },
  { route: '/app/platform/tenants/new', label: "New", dynamic: false, roles: ['ROLE_PLATFORM_ADMIN'], permissions: ['platform:tenant:create'] },
  { route: '/app/positivity', label: "", dynamic: false, roles: ['ROLE_ADMIN'], permissions: ['supplier:profile:read'] },
  { route: '/app/positivity/exchanges', label: "Exchanges", dynamic: false, roles: ['ROLE_ADMIN'], permissions: ['supplier:audit:read'] },
  { route: '/app/positivity/exchanges/:exchangeId', label: "Exchanges", dynamic: true, roles: ['ROLE_ADMIN'], permissions: ['supplier:audit:read'] },
  { route: '/app/positivity/manual-review', label: "Manual Review", dynamic: false, roles: ['ROLE_ADMIN'], permissions: ['supplier:transmission:read'] },
  { route: '/app/positivity/profiles/:vendorProfileId', label: "Profiles", dynamic: true, roles: ['ROLE_ADMIN'], permissions: ['supplier:profile:read'] },
  { route: '/app/product', label: "", dynamic: false },
  { route: '/app/product/bulk-import/catalog', label: "Catalog", dynamic: false, permissions: ['bulkImport:upload:execute'] },
  { route: '/app/product/bulk-import/price', label: "Price", dynamic: false, permissions: ['bulkImport:upload:execute'] },
  { route: '/app/product/catalog', label: "Catalog", dynamic: false, permissions: ['catalog:product:view'] },
  { route: '/app/product/catalog/:productId', label: "Catalog", dynamic: true, permissions: ['catalog:product:view'] },
  { route: '/app/product/catalog/enrichment/review/:treadDesignId', label: "Review", dynamic: true, permissions: ['catalog:tread_design:view'] },
  { route: '/app/product/catalog/enrichment/unmatched', label: "Unmatched", dynamic: false, permissions: ['catalog:tread_design:view'] },
  { route: '/app/product/inventory/availability', label: "Availability", dynamic: false, permissions: ['inventory:availability:read'] },
  { route: '/app/product/inventory/feeds', label: "Feeds", dynamic: false },
  { route: '/app/product/location/locations-roster', label: "Locations Roster", dynamic: false, permissions: ['location:read'] },
  { route: '/app/product/pricing/location-overrides', label: "Location Overrides", dynamic: false, permissions: ['catalog:location_price_override:read'] },
  { route: '/app/product/pricing/msrp', label: "Msrp", dynamic: false, permissions: ['catalog:msrp:read'] },
  { route: '/app/product/pricing/price-books', label: "Price Books", dynamic: false, permissions: ['catalog:price_book:read'] },
  { route: '/app/security', label: "", dynamic: false, roles: ['ROLE_ADMIN'], permissions: ['security:role:view'] },
  { route: '/app/security/audit', label: "Audit", dynamic: false, roles: ['ROLE_ADMIN'], permissions: ['shop:schedule:view', 'appointments:view'] },
  { route: '/app/security/audit-logs', label: "Audit Logs", dynamic: false, roles: ['ROLE_ADMIN'], permissions: ['security:audit:view'] },
  { route: '/app/security/permissions', label: "Permissions", dynamic: false, roles: ['ROLE_ADMIN'], permissions: ['security:permission:view'] },
  { route: '/app/security/roles/:name', label: "Roles", dynamic: true, roles: ['ROLE_ADMIN'], permissions: ['security:role:view'] },
  { route: '/app/security/users/provision', label: "Provision", dynamic: false, roles: ['ROLE_ADMIN'], permissions: ['security:user:create'] },
  { route: '/app/shopmgmt', label: "", dynamic: false },
  { route: '/app/shopmgmt/appointments/:id/assignments', label: "Assignments", dynamic: true, permissions: ['appointments:view', 'shop:schedule:view'] },
  { route: '/app/shopmgmt/appointments/:id/dispatch-assign', label: "Dispatch Assign", dynamic: true, permissions: ['shop:bay:assign'] },
  { route: '/app/shopmgmt/appointments/:id/edit', label: "Edit", dynamic: true, permissions: ['appointments:view', 'shop:schedule:view'] },
  { route: '/app/shopmgmt/appointments/:id/override-conflict', label: "Override Conflict", dynamic: true, permissions: ['shop:schedule:edit', 'appointments:reschedule'] },
  { route: '/app/shopmgmt/appointments/:id/reschedule', label: "Reschedule", dynamic: true, permissions: ['appointments:reschedule'] },
  { route: '/app/shopmgmt/appointments/new', label: "New", dynamic: false, permissions: ['appointments:create', 'shop:schedule:edit'] },
  { route: '/app/shopmgmt/appointments/new/crm', label: "Crm", dynamic: false, permissions: ['appointments:create', 'shop:schedule:edit'] },
  { route: '/app/shopmgmt/dispatch-board', label: "Dispatch Board", dynamic: false, permissions: ['workorder:dashboard:view'] },
  { route: '/app/shopmgmt/mechanics/availability', label: "Availability", dynamic: false, permissions: ['people:availability:view'] },
  { route: '/app/shopmgmt/mechanics/roster', label: "Roster", dynamic: false, permissions: ['shop:technician:view'] },
  { route: '/app/shopmgmt/schedule', label: "Schedule", dynamic: false, permissions: ['shop:schedule:view'] },
  { route: '/app/shopmgmt/shop-dashboard', label: "Shop Dashboard", dynamic: false, permissions: ['workorder:dashboard:view'] },
  { route: '/app/sitemap', label: "", dynamic: false },
  { route: '/app/workexec', label: "", dynamic: false },
  { route: '/app/workexec/estimate-list', label: "Estimate List", dynamic: false, permissions: ['workorder:estimate:view'] },
  { route: '/app/workexec/estimates/:estimateId', label: "Estimates", dynamic: true, permissions: ['workorder:estimate:view'] },
  { route: '/app/workexec/estimates/:estimateId/approval/:approvalId', label: "Approval", dynamic: true, permissions: ['workorder:estimate:view'] },
  { route: '/app/workexec/estimates/:estimateId/approval/digital', label: "Digital", dynamic: true, permissions: ['workorder:estimate:approve'] },
  { route: '/app/workexec/estimates/:estimateId/approval/in-person', label: "In Person", dynamic: true, permissions: ['workorder:estimate:approve'] },
  { route: '/app/workexec/estimates/:estimateId/approval/partial', label: "Partial", dynamic: true, permissions: ['workorder:estimate:approve'] },
  { route: '/app/workexec/estimates/:estimateId/approval/submit', label: "Submit", dynamic: true, permissions: ['workorder:estimate:submit'] },
  { route: '/app/workexec/estimates/:estimateId/labor', label: "Labor", dynamic: true, permissions: ['workorder:estimate:view'] },
  { route: '/app/workexec/estimates/:estimateId/parts', label: "Parts", dynamic: true, permissions: ['workorder:estimate:view'] },
  { route: '/app/workexec/estimates/:estimateId/revise', label: "Revise", dynamic: true, permissions: ['workorder:estimate:reopen'] },
  { route: '/app/workexec/estimates/:estimateId/summary', label: "Summary", dynamic: true, permissions: ['workorder:estimate:view'] },
  { route: '/app/workexec/estimates/new', label: "New", dynamic: false, permissions: ['workorder:estimate:create'] },
  { route: '/app/workexec/timer', label: "Timer", dynamic: false, permissions: ['workorder:labor:view'] },
  { route: '/app/workexec/travel-time', label: "Travel Time", dynamic: false, permissions: ['workorder:labor:add'] },
  { route: '/app/workexec/wip-status', label: "Wip Status", dynamic: false, permissions: ['workorder:wip:view'] },
  { route: '/app/workexec/workorders/:id/operational-context', label: "Operational Context", dynamic: true },
  { route: '/app/workexec/workorders/:workorderId', label: "Workorders", dynamic: true },
  { route: '/app/workexec/workorders/:workorderId/assign', label: "Assign", dynamic: true, permissions: ['workorder:workorder:assign-technician'] },
  { route: '/app/workexec/workorders/:workorderId/change-requests', label: "Change Requests", dynamic: true, permissions: ['workorder:change_request:view'] },
  { route: '/app/workexec/workorders/:workorderId/finalize', label: "Finalize", dynamic: true, permissions: ['workorder:workorder:view'] },
  { route: '/app/workexec/workorders/:workorderId/invoice-finalization', label: "Invoice Finalization", dynamic: true },
  { route: '/app/workexec/workorders/:workorderId/labor', label: "Labor", dynamic: true, permissions: ['workorder:labor:view'] },
  { route: '/app/workexec/workorders/:workorderId/parts', label: "Parts", dynamic: true, permissions: ['workorder:parts:view'] },
  { route: '/app/workexec/workorders/from-appointment', label: "From Appointment", dynamic: false, permissions: ['workorder:estimate:create'] },
];

// The access requirement on each group's mount route under /app — what admits
// or refuses the whole group, and so its section root in the sitemap.
export const SITE_MAP_MOUNTS: readonly SiteMapMountEntry[] = [
  { route: '/app' },
  { route: '/app/accounting', permissions: ['accounting:je:view', 'accounting:je:create', 'accounting:je:post', 'accounting:ap:view', 'accounting:ap:pay', 'accounting:coa:view', 'accounting:coa:create', 'accounting:coa:edit', 'accounting:events:view', 'accounting:events:submit', 'accounting:events:retry', 'accounting:events:reprocess', 'accounting:export:request', 'accounting:export:view', 'accounting:ap:approve', 'accounting:ap:reject', 'accounting:coa:deactivate', 'accounting:je:reverse', 'accounting:mapping:view', 'accounting:mapping:create', 'accounting:mapping:edit', 'accounting:mapping:deactivate', 'accounting:posting_rules:view', 'accounting:posting_rules:create', 'accounting:posting_rules:publish', 'accounting:posting_rules:archive', 'accounting:credit-memo:create', 'accounting:credit-memo:read', 'accounting:default-mapping:create', 'accounting:default-mapping:delete', 'accounting:default-mapping:edit', 'accounting:default-mapping:view', 'accounting:gl-mapping:create', 'accounting:gl-mapping:resolve', 'accounting:mapping-key:create', 'accounting:mapping-key:deactivate', 'accounting:mapping-key:edit', 'accounting:mapping-key:view', 'accounting:payment:apply', 'accounting:payment:reverse', 'accounting:posting-category:create', 'accounting:posting-category:deactivate', 'accounting:posting-category:edit', 'accounting:posting-category:view', 'accounting:report:export', 'accounting:time:export', 'reporting:view:financial-statements', 'accounting:period:close', 'accounting:period:reopen', 'accounting:period:view', 'accounting:period:hard_lock', 'accounting:period:override', 'accounting:reconciliation:adjust', 'accounting:reconciliation:view', 'accounting:customer-credit:view', 'accounting:customer-credit:apply', 'accounting:customer-credit:refund', 'accounting:tax-snapshot:freeze', 'accounting:credit-memo:void', 'accounting:analytics:view', 'accounting:gl:reconcile'] },
  { route: '/app/admin', roles: ['ROLE_ADMIN'] },
  { route: '/app/billing', permissions: ['invoice:manage', 'invoice:billing-rules', 'invoice:finalize', 'accounting:payment:apply', 'accounting:payment:reverse', 'invoice:finalize:override', 'accounting:customer-credit:view', 'accounting:customer-credit:apply', 'accounting:customer-credit:refund', 'invoice:invoice:view', 'invoice:analytics:view'] },
  { route: '/app/bulk-import', permissions: ['bulkImport:upload:execute', 'bulkImport:status:read'] },
  { route: '/app/crm', permissions: ['accounting:events:view', 'crm:party:view', 'crm:party:search', 'crm:party:create', 'crm:party:edit', 'crm:party:deactivate', 'crm:party:merge', 'crm:contact:view', 'crm:contact:create', 'crm:contact:edit', 'crm:contact:delete', 'crm:contact_role:view', 'crm:contact_role:assign', 'crm:contact_role:revoke', 'crm:contact_preference:view', 'crm:contact_preference:edit', 'crm:vehicle:view', 'crm:vehicle:search', 'crm:vehicle:create', 'crm:vehicle:edit', 'crm:vehicle:deactivate', 'crm:vehicle_party_association:create', 'crm:vehicle_party_association:view', 'crm:vehicle_party_association:edit', 'crm:vehicle_preference:view', 'crm:vehicle_preference:edit', 'crm:processing_log:view', 'crm:suspense:view', 'crm:integration:audit', 'vehicle-fitment:hint:view', 'vehicle-fitment:hint:create', 'vehicle-fitment:hint:update', 'vehicle-fitment:hint:delete', 'vehicle-fitment:catalog:view', 'vehicle-inventory:registry:view', 'vehicle-inventory:registry:create', 'vehicle-inventory:registry:update', 'vehicle-inventory:registry:delete', 'vehicle-inventory:preferences:manage', 'vehicle-inventory:search:view', 'bulkImport:upload:execute', 'crm:billing_rules:edit', 'crm:person:create', 'crm:person:read', 'crm:relationship:create', 'crm:relationship:delete', 'crm:relationship:read', 'crm:relationship:update', 'crm:promotion_redemption:record', 'crm:promotion_redemption:view', 'crm:consent:manage', 'crm:consent:view', 'crm:interaction:view', 'crm:segment:manage', 'crm:segment:resolve', 'crm:segment:view', 'crm:suppression:manage', 'crm:suppression:view', 'crm:tag:assign', 'crm:tag:manage', 'crm:tag:view', 'crm:followup:manage', 'crm:followup:view', 'crm:inquiry:manage', 'crm:inquiry:view', 'crm:interaction:manage', 'crm:fact:replay'] },
  { route: '/app/inventory', permissions: ['inventory:adjustment:create', 'inventory:adjustment:approve', 'inventory:adjustment:view', 'inventory:putaway:override_location_compatibility', 'inventory:putaway:override_location_capacity', 'inventory:cycle_count:initiate', 'inventory:cycle_count:view', 'inventory:cycle_count:complete', 'inventory:on_hand:view', 'inventory:on_hand:search', 'inventory:receiving:create', 'inventory:receiving:view', 'inventory:receiving:complete', 'inventory:issue:parts', 'inventory:override:part-match', 'inventory:purchase_order:create', 'inventory:purchase_order:view', 'inventory:purchase_order:approve', 'inventory:purchase_order:receive', 'inventory:asn:create', 'inventory:asn:view', 'inventory:goods_receipt:create', 'inventory:goods_receipt:view', 'inventory:goods_receipt:override', 'inventory:allocations:reallocate', 'inventory:shortages:resolve', 'security:permission:view', 'bulkImport:upload:execute', 'inventory:ledger:view', 'inventory:location:admin', 'inventory:location:view', 'inventory:pick_list:create', 'inventory:pick_list:execute', 'inventory:pick_list:view', 'inventory:putaway:claim', 'inventory:putaway:execute', 'inventory:putaway:generate', 'inventory:putaway:view', 'inventory:return:view', 'inventory:return:write', 'inventory:shortage:resolve', 'inventory:shortage:view', 'inventory:stock_movement:create', 'inventory:availability:read', 'inventory:location:sync', 'inventory:scrap:approve', 'inventory:scrap:create', 'inventory:scrap:view', 'inventory:transfer:create', 'inventory:transfer:dispatch', 'inventory:transfer:receive', 'inventory:transfer:short_close', 'inventory:transfer:view', 'inventory:lot:manage', 'inventory:valuation:view', 'inventory:valuation:adjust', 'inventory:supplier_stock_hint:view', 'inventory:replenishment:manage', 'order:purchase_order:create', 'order:purchase_order:view', 'inventory:adjustment:override', 'inventory:cycle_count_tolerance:manage', 'inventory:availability:search', 'inventory:putaway_rule:manage', 'inventory:putaway_rule:view'] },
  { route: '/app/location', permissions: ['location:read', 'location:write', 'location:bay:read', 'location:bay:manage', 'location:mobile-unit:read', 'location:mobile-unit:manage', 'location:service-area:read', 'location:service-area:manage', 'location:travel-buffer-policy:read', 'location:travel-buffer-policy:manage', 'bulkImport:upload:execute', 'inventory:location:view'] },
  { route: '/app/order', permissions: ['order:order:view', 'order:order:create', 'order:order:edit', 'order:order:cancel', 'order:line:view', 'order:line:create', 'order:line:edit', 'order:line:delete', 'order:line:enter_manual_price', 'order:price_override:view', 'order:price_override:apply', 'order:price_override:approve', 'order:price_override:reject', 'order:order:discount', 'order:order:quote', 'order:order:checkout', 'order:order:void', 'order:order:charge_on_account', 'order:session:open', 'order:session:view', 'order:session:cash_movement', 'order:session:close', 'order:session:approve_variance', 'order:return:create', 'order:return:approve', 'order:return:view', 'order:purchase_order:approve', 'order:purchase_order:create', 'order:purchase_order:view', 'order:purchase_order:transmit', 'order:purchase_order:availability_view'] },
  { route: '/app/people', permissions: ['people:employee:view', 'people:employee:create', 'people:employee:edit', 'people:employee:deactivate', 'people:role:view', 'people:role:assign', 'people:role:revoke', 'people:skill:view', 'people:skill:assign', 'people:skill:edit', 'people:person:view', 'people:person:create', 'people:person:edit', 'people:person:delete', 'people:userLink:view', 'people:userLink:write', 'bulkImport:upload:execute', 'accounting:export:view', 'timekeeping:work_session:create', 'timekeeping:work_session:stop', 'timekeeping:work_session:break_start', 'timekeeping:work_session:break_stop', 'timekeeping:overlap_override', 'accounting:time:export', 'people:availability:view', 'people:timeAdjustment:approve', 'people:timeAdjustment:create', 'people:timeAdjustment:view', 'people:timeEntry:approve', 'people:timeEntry:reject', 'people:timeException:acknowledge', 'people:timeException:create', 'people:timeException:resolve', 'people:timeException:view', 'people:timekeeping:approve', 'people:timekeeping:reject', 'people:timekeeping:view', 'TimeEntry:Approve', 'TimeEntry:Reject', 'people-contact:person:view', 'people-contact:person:create', 'people-contact:person:edit', 'people-contact:person:delete', 'people-contact:role:view', 'people-contact:role:assign', 'people-contact:role:revoke', 'people-contact:userLink:view', 'people-contact:userLink:write', 'people:compliance:view', 'people-contact:organization:edit', 'people-contact:organization:view', 'people:timePeriod:create', 'people:timePeriod:transition', 'people:timeEntry:view', 'people:self:view', 'people:employee_pii:view'] },
  { route: '/app/platform', roles: ['ROLE_PLATFORM_ADMIN'], permissions: ['platform:tenant:read', 'platform:tenant:create'] },
  { route: '/app/positivity', roles: ['ROLE_ADMIN'] },
  { route: '/app/product', permissions: ['catalog:product:view', 'catalog:product:create', 'catalog:product:edit', 'catalog:product:delete', 'product:lifecycle:update', 'product:lifecycle:override_discontinued', 'catalog:category:view', 'catalog:category:create', 'catalog:category:edit', 'catalog:category:delete', 'catalog:service_type:view', 'catalog:service_type:create', 'catalog:service_type:edit', 'catalog:variant:view', 'catalog:variant:create', 'catalog:variant:edit', 'location:read', 'pricing:price_book:view', 'pricing:price_book:create', 'pricing:price_book:edit', 'pricing:price_book:delete', 'pricing:normalization:view', 'pricing:normalization:edit', 'pricing:restrictions:view', 'pricing:restrictions:edit', 'pricing:rule:view', 'pricing:rule:create', 'pricing:rule:edit', 'pricing:rule:delete', 'catalog:supplier_cost:read', 'catalog:supplier_cost:write', 'catalog:msrp:read', 'catalog:msrp:write', 'catalog:price_book:read', 'catalog:price_book:write', 'bulkImport:upload:execute', 'pricing:base_price:create', 'inventory:availability:read', 'pricing:override:approve', 'pricing:restriction:manage', 'pricing:restriction:override', 'pricing:promotion:apply', 'pricing:promotion:manage', 'pricing:promotion:view', 'catalog:item_cost:update', 'catalog:guardrail_policy:write', 'catalog:location_price_override:read', 'catalog:location_price_override:write', 'catalog:non_inventory:view', 'catalog:substitution_group:view', 'catalog:substitution_group:edit', 'catalog:catalog_grouping:view', 'catalog:catalog_grouping:edit', 'catalog:catalog_grouping:delete', 'catalog:uom_conversion:view', 'catalog:uom_conversion:edit', 'catalog:product_uom:view', 'catalog:product_uom:edit', 'catalog:item_cost:read', 'catalog:tread_design:view', 'catalog:fact:replay', 'catalog:labor_standard:manage', 'catalog:labor_standard:view', 'catalog:labor_standard:import', 'catalog:labor_time:resolve', 'catalog:tread_design:resolve', 'pricing:labor_rate:manage', 'pricing:labor_rate:view', 'pricing:labor_rate:quote', 'catalog:service_package:manage', 'catalog:service_package:view', 'catalog:service:ingest'] },
  { route: '/app/security', roles: ['ROLE_ADMIN'] },
  { route: '/app/shopmgmt', permissions: ['shop:location:view', 'shop:location:create', 'shop:location:edit', 'shop:location:deactivate', 'shop:bay:view', 'shop:bay:create', 'shop:bay:edit', 'shop:bay:assign', 'shop:schedule:view', 'shop:schedule:edit', 'appointments:create', 'appointments:view', 'appointments:reschedule', 'appointments:cancel', 'workorder:dashboard:view', 'people:availability:view', 'shop:technician:view', 'shop:dashboard:view'] },
  { route: '/app/sitemap' },
  { route: '/app/workexec', permissions: ['workorder:workorder:view', 'workorder:workorder:create', 'workorder:workorder:edit', 'workorder:workorder:delete', 'workorder:workorder:start', 'workorder:workorder:complete', 'workorder:workorder:reopen_completed', 'workorder:workorder:approve', 'workorder:estimate:view', 'workorder:estimate:create', 'workorder:estimate:edit', 'workorder:estimate:delete', 'workorder:estimate:approve', 'workorder:estimate:decline', 'workorder:estimate:reopen', 'workorder:estimate:calculate', 'workorder:estimate_item:view', 'workorder:estimate_item:add', 'workorder:estimate_item:edit', 'workorder:estimate_item:delete', 'workorder:estimate_snapshot:create', 'workorder:estimate_snapshot:view', 'workorder:change_request:view', 'workorder:change_request:create', 'workorder:change_request:approve', 'workorder:change_request:decline', 'workorder:change_request:emergency_override', 'workorder:approval_config:view', 'workorder:approval_config:create', 'workorder:approval_config:edit', 'workorder:approval_config:delete', 'workorder:invoice:view', 'workorder:invoice:create', 'workorder:labor:view', 'workorder:labor:add', 'workorder:parts:view', 'workorder:parts:add', 'workorder:wip:view', 'workorder:wip:view_all_locations', 'workorder:parts:consume', 'workorder:dashboard:view', 'workorder:estimate:submit', 'workorder:estimate:promote', 'workorder:workorder:assign-technician', 'workorder:workorder:generate_invoice', 'workorder:start', 'workorder:operationalContext:override', 'workorder:timeEntry:approve', 'workorder:timeEntry:reject', 'workorder:labor:add_on_behalf', 'workorder:events:replay', 'workorder:fleet_auth:request', 'workorder:fleet_auth:resolve', 'workorder:financials:view', 'workorder:analytics:view', 'workorder:note:add', 'workorder:note:view', 'workorder:labor_intelligence:view'] },
];
