// GENERATED — do not edit by hand.
// Source: src/app/app.routes.ts + feature *.routes.ts (parsed by scripts/sitemap/extract-routes.mjs)
// Regenerate: npm run sitemap:routes:generate
//
// Every reachable route under the authenticated /app shell, with derived label,
// dynamic-param flag, and required roles. Consumed by the sitemap page.
import type { SiteMapRouteEntry } from './models/site-map-section.model';

export const SITE_MAP_ROUTES: readonly SiteMapRouteEntry[] = [
  { route: '/app', label: "", dynamic: false },
  { route: '/app/accounting', label: "", dynamic: false },
  { route: '/app/accounting/credit-memos', label: "Credit Memos", dynamic: false },
  { route: '/app/accounting/credit-memos/:memoId', label: "Credit Memos", dynamic: true },
  { route: '/app/accounting/credit-memos/new', label: "New", dynamic: false },
  { route: '/app/accounting/events', label: "Events", dynamic: false },
  { route: '/app/accounting/events/:eventId', label: "Events", dynamic: true },
  { route: '/app/accounting/events/contract', label: "Contract", dynamic: false },
  { route: '/app/accounting/events/submit', label: "Submit", dynamic: false },
  { route: '/app/accounting/invoices/:invoiceId/payment-status', label: "Payment Status", dynamic: true },
  { route: '/app/accounting/payments/apply', label: "Apply", dynamic: false },
  { route: '/app/accounting/posting-rules', label: "Posting Rules", dynamic: false },
  { route: '/app/accounting/posting-rules/:ruleSetId', label: "Posting Rules", dynamic: true },
  { route: '/app/accounting/reports/labor-overhead', label: "Labor Overhead", dynamic: false },
  { route: '/app/accounting/vendor-payments', label: "Vendor Payments", dynamic: false },
  { route: '/app/accounting/vendor-payments/:paymentId', label: "Vendor Payments", dynamic: true },
  { route: '/app/accounting/vendor-payments/new', label: "New", dynamic: false },
  { route: '/app/admin', label: "", dynamic: false, roles: ['ROLE_ADMIN'] },
  { route: '/app/billing', label: "", dynamic: false },
  { route: '/app/billing/invoices/:invoiceId', label: "Invoices", dynamic: true },
  { route: '/app/billing/invoices/:invoiceId/payment-capture', label: "Payment Capture", dynamic: true },
  { route: '/app/billing/invoices/:invoiceId/payments/:paymentId/void-refund', label: "Void Refund", dynamic: true },
  { route: '/app/billing/invoices/:invoiceId/receipts', label: "Receipts", dynamic: true },
  { route: '/app/billing/invoices/:invoiceId/receipts/:receiptId', label: "Receipts", dynamic: true },
  { route: '/app/bulk-import/jobs', label: "Jobs", dynamic: false },
  { route: '/app/bulk-import/jobs/:jobId', label: "Jobs", dynamic: true },
  { route: '/app/crm', label: "", dynamic: false },
  { route: '/app/crm/bulk-import/customer', label: "Customer", dynamic: false },
  { route: '/app/crm/bulk-import/vehicle-fitment', label: "Vehicle Fitment", dynamic: false },
  { route: '/app/crm/bulk-import/vehicle-inventory', label: "Vehicle Inventory", dynamic: false },
  { route: '/app/crm/create-commercial-account', label: "Create Commercial Account", dynamic: false },
  { route: '/app/crm/create-individual-person', label: "Create Individual Person", dynamic: false },
  { route: '/app/crm/crm-snapshot/:partyId', label: "Crm Snapshot", dynamic: true },
  { route: '/app/crm/customers', label: "Customers", dynamic: false },
  { route: '/app/crm/integration/events', label: "Events", dynamic: false },
  { route: '/app/crm/merge-parties', label: "Merge Parties", dynamic: false },
  { route: '/app/crm/party/:partyId', label: "Party", dynamic: true },
  { route: '/app/crm/party/:partyId/add-vehicle', label: "Add Vehicle", dynamic: true },
  { route: '/app/crm/party/:partyId/billing-rules', label: "Billing Rules", dynamic: true },
  { route: '/app/crm/party/:partyId/contacts', label: "Contacts", dynamic: true },
  { route: '/app/crm/snapshot', label: "Snapshot", dynamic: false },
  { route: '/app/inventory', label: "", dynamic: false },
  { route: '/app/inventory/availability', label: "Availability", dynamic: false },
  { route: '/app/inventory/bulk-import/stock', label: "Stock", dynamic: false },
  { route: '/app/inventory/by-location', label: "By Location", dynamic: false },
  { route: '/app/inventory/by-location/:locationId', label: "By Location", dynamic: true },
  { route: '/app/inventory/by-location/site/:siteId', label: "Site", dynamic: true },
  { route: '/app/inventory/counts/adjustments', label: "Adjustments", dynamic: false },
  { route: '/app/inventory/counts/execute', label: "Execute", dynamic: false },
  { route: '/app/inventory/counts/plans', label: "Plans", dynamic: false },
  { route: '/app/inventory/counts/plans/new', label: "New", dynamic: false },
  { route: '/app/inventory/fulfillment/workorders/:workorderId/consume-items', label: "Consume Items", dynamic: true },
  { route: '/app/inventory/fulfillment/workorders/:workorderId/pick-execute', label: "Pick Execute", dynamic: true },
  { route: '/app/inventory/fulfillment/workorders/:workorderId/pick-list', label: "Pick List", dynamic: true },
  { route: '/app/inventory/fulfillment/workorders/:workorderId/return-to-stock', label: "Return To Stock", dynamic: true },
  { route: '/app/inventory/fulfillment/workorders/:workorderId/shortage-resolution', label: "Shortage Resolution", dynamic: true },
  { route: '/app/inventory/ledger', label: "Ledger", dynamic: false },
  { route: '/app/inventory/ledger/:ledgerEntryId', label: "Ledger", dynamic: true },
  { route: '/app/inventory/purchase-orders', label: "Purchase Orders", dynamic: false },
  { route: '/app/inventory/purchase-orders/:poId', label: "Purchase Orders", dynamic: true },
  { route: '/app/inventory/purchase-orders/:poId/edit', label: "Edit", dynamic: true },
  { route: '/app/inventory/purchase-orders/new', label: "New", dynamic: false },
  { route: '/app/inventory/putaway/tasks', label: "Tasks", dynamic: false },
  { route: '/app/inventory/putaway/tasks/:taskId', label: "Tasks", dynamic: true },
  { route: '/app/inventory/receiving/cross-dock', label: "Cross Dock", dynamic: false },
  { route: '/app/inventory/receiving/receive-into-staging', label: "Receive Into Staging", dynamic: false },
  { route: '/app/inventory/replenishment/tasks', label: "Tasks", dynamic: false },
  { route: '/app/inventory/security/permissions', label: "Permissions", dynamic: false },
  { route: '/app/location', label: "", dynamic: false },
  { route: '/app/location/bays', label: "Bays", dynamic: false },
  { route: '/app/location/bulk-import/location', label: "Location", dynamic: false },
  { route: '/app/location/location-sync', label: "Location Sync", dynamic: false },
  { route: '/app/location/locations', label: "Locations", dynamic: false },
  { route: '/app/location/locations/:id', label: "Locations", dynamic: true },
  { route: '/app/location/locations/:locationId/defaults', label: "Defaults", dynamic: true },
  { route: '/app/location/locations/new', label: "New", dynamic: false },
  { route: '/app/location/mobile-units', label: "Mobile Units", dynamic: false },
  { route: '/app/location/storage-locations', label: "Storage Locations", dynamic: false },
  { route: '/app/order/:orderId/cancel', label: "Cancel", dynamic: true },
  { route: '/app/order/:orderId/price-override/:lineId', label: "Price Override", dynamic: true },
  { route: '/app/order/cart', label: "Cart", dynamic: false },
  { route: '/app/order/cart/:orderId', label: "Cart", dynamic: true },
  { route: '/app/people', label: "", dynamic: false },
  { route: '/app/people/bulk-import/people', label: "People", dynamic: false },
  { route: '/app/people/directory', label: "Directory", dynamic: false },
  { route: '/app/people/employees/:id', label: "Employees", dynamic: true },
  { route: '/app/people/employees/:id/offboard', label: "Offboard", dynamic: true },
  { route: '/app/people/employees/new', label: "New", dynamic: false },
  { route: '/app/people/identity-compliance', label: "Identity Compliance", dynamic: false, roles: ['ROLE_ADMIN'] },
  { route: '/app/people/person/:personId/locations', label: "Locations", dynamic: true },
  { route: '/app/people/rbac/:personUuid', label: "Rbac", dynamic: true },
  { route: '/app/people/timekeeping/approval', label: "Approval", dynamic: false },
  { route: '/app/people/timekeeping/discrepancy', label: "Discrepancy", dynamic: false },
  { route: '/app/people/timekeeping/export', label: "Export", dynamic: false },
  { route: '/app/people/timekeeping/work-session', label: "Work Session", dynamic: false },
  { route: '/app/people/timekeeping/work-session/:sessionId/submit', label: "Submit", dynamic: true },
  { route: '/app/positivity', label: "", dynamic: false, roles: ['ROLE_ADMIN'] },
  { route: '/app/positivity/exchanges', label: "Exchanges", dynamic: false, roles: ['ROLE_ADMIN'] },
  { route: '/app/positivity/exchanges/:exchangeId', label: "Exchanges", dynamic: true, roles: ['ROLE_ADMIN'] },
  { route: '/app/positivity/profiles/:vendorProfileId', label: "Profiles", dynamic: true, roles: ['ROLE_ADMIN'] },
  { route: '/app/product', label: "", dynamic: false },
  { route: '/app/product/bulk-import/catalog', label: "Catalog", dynamic: false },
  { route: '/app/product/bulk-import/price', label: "Price", dynamic: false },
  { route: '/app/product/catalog', label: "Catalog", dynamic: false },
  { route: '/app/product/catalog/:productId', label: "Catalog", dynamic: true },
  { route: '/app/product/inventory/availability', label: "Availability", dynamic: false },
  { route: '/app/product/inventory/feeds', label: "Feeds", dynamic: false },
  { route: '/app/product/location/locations-roster', label: "Locations Roster", dynamic: false },
  { route: '/app/product/pricing/location-overrides', label: "Location Overrides", dynamic: false },
  { route: '/app/product/pricing/msrp', label: "Msrp", dynamic: false },
  { route: '/app/product/pricing/price-books', label: "Price Books", dynamic: false },
  { route: '/app/security', label: "", dynamic: false, roles: ['ROLE_ADMIN'] },
  { route: '/app/security/audit', label: "Audit", dynamic: false, roles: ['ROLE_ADMIN'] },
  { route: '/app/security/audit-logs', label: "Audit Logs", dynamic: false, roles: ['ROLE_ADMIN'] },
  { route: '/app/security/permissions', label: "Permissions", dynamic: false, roles: ['ROLE_ADMIN'] },
  { route: '/app/security/roles/:name', label: "Roles", dynamic: true, roles: ['ROLE_ADMIN'] },
  { route: '/app/security/users/provision', label: "Provision", dynamic: false, roles: ['ROLE_ADMIN'] },
  { route: '/app/shopmgmt', label: "", dynamic: false },
  { route: '/app/shopmgmt/appointments/:id/assignments', label: "Assignments", dynamic: true },
  { route: '/app/shopmgmt/appointments/:id/dispatch-assign', label: "Dispatch Assign", dynamic: true },
  { route: '/app/shopmgmt/appointments/:id/edit', label: "Edit", dynamic: true },
  { route: '/app/shopmgmt/appointments/:id/override-conflict', label: "Override Conflict", dynamic: true },
  { route: '/app/shopmgmt/appointments/:id/reschedule', label: "Reschedule", dynamic: true },
  { route: '/app/shopmgmt/appointments/new', label: "New", dynamic: false },
  { route: '/app/shopmgmt/appointments/new/crm', label: "Crm", dynamic: false },
  { route: '/app/shopmgmt/dispatch-board', label: "Dispatch Board", dynamic: false },
  { route: '/app/shopmgmt/mechanics/availability', label: "Availability", dynamic: false },
  { route: '/app/shopmgmt/mechanics/roster', label: "Roster", dynamic: false },
  { route: '/app/shopmgmt/schedule', label: "Schedule", dynamic: false },
  { route: '/app/sitemap', label: "", dynamic: false },
  { route: '/app/workexec', label: "", dynamic: false },
  { route: '/app/workexec/estimate-list', label: "Estimate List", dynamic: false },
  { route: '/app/workexec/estimates/:estimateId', label: "Estimates", dynamic: true },
  { route: '/app/workexec/estimates/:estimateId/approval/:approvalId', label: "Approval", dynamic: true },
  { route: '/app/workexec/estimates/:estimateId/approval/digital', label: "Digital", dynamic: true },
  { route: '/app/workexec/estimates/:estimateId/approval/in-person', label: "In Person", dynamic: true },
  { route: '/app/workexec/estimates/:estimateId/approval/partial', label: "Partial", dynamic: true },
  { route: '/app/workexec/estimates/:estimateId/approval/submit', label: "Submit", dynamic: true },
  { route: '/app/workexec/estimates/:estimateId/labor', label: "Labor", dynamic: true },
  { route: '/app/workexec/estimates/:estimateId/parts', label: "Parts", dynamic: true },
  { route: '/app/workexec/estimates/:estimateId/revise', label: "Revise", dynamic: true },
  { route: '/app/workexec/estimates/:estimateId/summary', label: "Summary", dynamic: true },
  { route: '/app/workexec/estimates/new', label: "New", dynamic: false },
  { route: '/app/workexec/timer', label: "Timer", dynamic: false },
  { route: '/app/workexec/travel-time', label: "Travel Time", dynamic: false },
  { route: '/app/workexec/wip-status', label: "Wip Status", dynamic: false },
  { route: '/app/workexec/workorders/:id/operational-context', label: "Operational Context", dynamic: true },
  { route: '/app/workexec/workorders/:workorderId', label: "Workorders", dynamic: true },
  { route: '/app/workexec/workorders/:workorderId/assign', label: "Assign", dynamic: true },
  { route: '/app/workexec/workorders/:workorderId/change-requests', label: "Change Requests", dynamic: true },
  { route: '/app/workexec/workorders/:workorderId/finalize', label: "Finalize", dynamic: true },
  { route: '/app/workexec/workorders/:workorderId/invoice-finalization', label: "Invoice Finalization", dynamic: true },
  { route: '/app/workexec/workorders/:workorderId/labor', label: "Labor", dynamic: true },
  { route: '/app/workexec/workorders/:workorderId/parts', label: "Parts", dynamic: true },
  { route: '/app/workexec/workorders/from-appointment', label: "From Appointment", dynamic: false },
];
