// GENERATED — do not edit by hand.
// Source: src/app/app.routes.ts + feature *.routes.ts (parsed by scripts/sitemap/extract-routes.mjs)
// Regenerate: npm run sitemap:routes:generate
//
// Every reachable route under the authenticated /app shell, with derived label,
// dynamic-param flag, and required roles/permissions. Consumed by the sitemap page.
import type { SiteMapRouteEntry } from './models/site-map-section.model';

export const SITE_MAP_ROUTES: readonly SiteMapRouteEntry[] = [
  { route: '/app', label: "", dynamic: false },
  { route: '/app/accounting', label: "", dynamic: false },
  { route: '/app/accounting/credit-memos', label: "Credit Memos", dynamic: false, permissions: ['accounting:credit-memo:read'] },
  { route: '/app/accounting/credit-memos/:memoId', label: "Credit Memos", dynamic: true, permissions: ['accounting:credit-memo:read'] },
  { route: '/app/accounting/credit-memos/new', label: "New", dynamic: false, permissions: ['accounting:credit-memo:create'] },
  { route: '/app/accounting/events', label: "Events", dynamic: false, permissions: ['accounting:events:view'] },
  { route: '/app/accounting/events/:eventId', label: "Events", dynamic: true, permissions: ['accounting:events:view'] },
  { route: '/app/accounting/events/contract', label: "Contract", dynamic: false, permissions: ['accounting:events:view'] },
  { route: '/app/accounting/events/submit', label: "Event Submission", dynamic: false, permissions: ['accounting:events:submit'] },
  { route: '/app/accounting/invoices/:invoiceId/payment-status', label: "Payment Status", dynamic: true, permissions: ['accounting:ap:view'] },
  { route: '/app/accounting/payables/vendor-invoices', label: "Vendor Invoices", dynamic: false, permissions: ['accounting:analytics:view'] },
  { route: '/app/accounting/payables/vendor-invoices/:billId', label: "Vendor Invoices", dynamic: true, permissions: ['accounting:ap:view'] },
  { route: '/app/accounting/payables/vendor-invoices/exceptions', label: "Exceptions", dynamic: false, permissions: ['accounting:analytics:view'] },
  { route: '/app/accounting/payments/apply', label: "Apply", dynamic: false, permissions: ['accounting:payment:apply'] },
  { route: '/app/accounting/posting-rules', label: "Posting Rules", dynamic: false, permissions: ['accounting:posting_rules:view'] },
  { route: '/app/accounting/posting-rules/:ruleSetId', label: "Posting Rules", dynamic: true, permissions: ['accounting:posting_rules:view'] },
  { route: '/app/accounting/reports/labor-overhead', label: "Labor Overhead", dynamic: false, permissions: ['reporting:view:financial-statements'] },
  { route: '/app/accounting/vendor-payments', label: "Vendor Payments", dynamic: false, permissions: ['accounting:ap:view'] },
  { route: '/app/accounting/vendor-payments/:paymentId', label: "Vendor Payments", dynamic: true, permissions: ['accounting:ap:view'] },
  { route: '/app/accounting/vendor-payments/new', label: "New", dynamic: false, permissions: ['accounting:ap:pay'] },
  { route: '/app/admin', label: "", dynamic: false, roles: ['ROLE_ADMIN'] },
  { route: '/app/billing', label: "", dynamic: false },
  { route: '/app/billing/invoices/:invoiceId', label: "Invoices", dynamic: true, permissions: ['invoice:invoice:view'] },
  { route: '/app/billing/invoices/:invoiceId/payment-capture', label: "Payment Capture", dynamic: true },
  { route: '/app/billing/invoices/:invoiceId/payments/:paymentId/void-refund', label: "Void Refund", dynamic: true },
  { route: '/app/billing/invoices/:invoiceId/receipts', label: "Receipts", dynamic: true },
  { route: '/app/billing/invoices/:invoiceId/receipts/:receiptId', label: "Receipts", dynamic: true },
  { route: '/app/bulk-import/jobs', label: "Jobs", dynamic: false, permissions: ['bulkImport:status:read'] },
  { route: '/app/bulk-import/jobs/:jobId', label: "Jobs", dynamic: true, permissions: ['bulkImport:status:read'] },
  { route: '/app/crm', label: "", dynamic: false },
  { route: '/app/crm/bulk-import/customer', label: "Customer", dynamic: false, permissions: ['bulkImport:upload:execute'] },
  { route: '/app/crm/bulk-import/vehicle-fitment', label: "Vehicle Fitment", dynamic: false, permissions: ['bulkImport:upload:execute'] },
  { route: '/app/crm/bulk-import/vehicle-inventory', label: "Vehicle Inventory", dynamic: false, permissions: ['bulkImport:upload:execute'] },
  { route: '/app/crm/create-commercial-account', label: "Create Commercial Account", dynamic: false, permissions: ['crm:party:create'] },
  { route: '/app/crm/create-individual-person', label: "Create Individual Person", dynamic: false, permissions: ['crm:person:create'] },
  { route: '/app/crm/crm-snapshot/:partyId', label: "Crm Snapshot", dynamic: true, permissions: ['crm:party:view'] },
  { route: '/app/crm/customers', label: "Customers", dynamic: false, permissions: ['crm:party:view'] },
  { route: '/app/crm/integration/events', label: "Events", dynamic: false, permissions: ['accounting:events:view'] },
  { route: '/app/crm/merge-parties', label: "Merge Parties", dynamic: false, permissions: ['crm:party:merge'] },
  { route: '/app/crm/party/:partyId', label: "Party", dynamic: true, permissions: ['crm:party:view'] },
  { route: '/app/crm/party/:partyId/add-vehicle', label: "Add Vehicle", dynamic: true, permissions: ['vehicle-inventory:registry:create'] },
  { route: '/app/crm/party/:partyId/billing-rules', label: "Billing Rules", dynamic: true, permissions: ['crm:party:view'] },
  { route: '/app/crm/party/:partyId/contacts', label: "Contacts", dynamic: true, permissions: ['crm:relationship:read'] },
  { route: '/app/crm/snapshot', label: "Snapshot", dynamic: false, permissions: ['crm:party:view'] },
  { route: '/app/inventory', label: "", dynamic: false },
  { route: '/app/inventory/availability', label: "Availability", dynamic: false, permissions: ['inventory:availability:read'] },
  { route: '/app/inventory/bulk-import/stock', label: "Stock", dynamic: false, permissions: ['bulkImport:upload:execute'] },
  { route: '/app/inventory/by-location', label: "By Location", dynamic: false, permissions: ['inventory:on_hand:view'] },
  { route: '/app/inventory/by-location/:locationId', label: "By Location", dynamic: true, permissions: ['inventory:on_hand:view'] },
  { route: '/app/inventory/by-location/site/:siteId', label: "Site", dynamic: true, permissions: ['inventory:on_hand:view'] },
  { route: '/app/inventory/counts/adjustments', label: "Adjustments", dynamic: false, permissions: ['inventory:adjustment:view', 'inventory:adjustment:approve'] },
  { route: '/app/inventory/counts/execute', label: "Execute", dynamic: false, permissions: ['inventory:cycle_count:view'] },
  { route: '/app/inventory/counts/plans', label: "Plans", dynamic: false, permissions: ['inventory:cycle_count:view'] },
  { route: '/app/inventory/counts/plans/new', label: "New", dynamic: false, permissions: ['inventory:cycle_count:initiate'] },
  { route: '/app/inventory/fulfillment/workorders/:workorderId/consume-items', label: "Consume Items", dynamic: true, permissions: ['inventory:pick_list:view'] },
  { route: '/app/inventory/fulfillment/workorders/:workorderId/pick-execute', label: "Pick Execute", dynamic: true, permissions: ['inventory:pick_list:view'] },
  { route: '/app/inventory/fulfillment/workorders/:workorderId/pick-list', label: "Pick List", dynamic: true, permissions: ['inventory:pick_list:view'] },
  { route: '/app/inventory/fulfillment/workorders/:workorderId/return-to-stock', label: "Return To Stock", dynamic: true, permissions: ['inventory:return:view'] },
  { route: '/app/inventory/fulfillment/workorders/:workorderId/shortage-resolution', label: "Shortage Resolution", dynamic: true, permissions: ['inventory:shortage:view'] },
  { route: '/app/inventory/ledger', label: "Ledger", dynamic: false, permissions: ['inventory:ledger:view'] },
  { route: '/app/inventory/ledger/:ledgerEntryId', label: "Ledger", dynamic: true, permissions: ['inventory:ledger:view'] },
  { route: '/app/inventory/purchase-orders', label: "Purchase Orders", dynamic: false, permissions: ['order:purchase_order:view'] },
  { route: '/app/inventory/purchase-orders/:poId', label: "Purchase Orders", dynamic: true, permissions: ['order:purchase_order:view'] },
  { route: '/app/inventory/purchase-orders/:poId/edit', label: "Edit", dynamic: true, permissions: ['order:purchase_order:create'] },
  { route: '/app/inventory/purchase-orders/new', label: "New", dynamic: false, permissions: ['order:purchase_order:create'] },
  { route: '/app/inventory/putaway/tasks', label: "Tasks", dynamic: false, permissions: ['inventory:putaway:view'] },
  { route: '/app/inventory/putaway/tasks/:taskId', label: "Tasks", dynamic: true, permissions: ['inventory:putaway:view'] },
  { route: '/app/inventory/receiving/cross-dock', label: "Cross Dock", dynamic: false, allPermissions: ['inventory:receiving:complete', 'inventory:issue:parts'] },
  { route: '/app/inventory/receiving/receive-into-staging', label: "Receive Into Staging", dynamic: false, permissions: ['inventory:receiving:view'] },
  { route: '/app/inventory/replenishment/tasks', label: "Tasks", dynamic: false, permissions: ['inventory:on_hand:view'] },
  { route: '/app/inventory/security/permissions', label: "Permissions", dynamic: false, permissions: ['security:permission:view'] },
  { route: '/app/location', label: "", dynamic: false },
  { route: '/app/location/bays', label: "Bays", dynamic: false, permissions: ['location:bay:read'] },
  { route: '/app/location/bulk-import/location', label: "Location", dynamic: false, permissions: ['bulkImport:upload:execute'] },
  { route: '/app/location/location-sync', label: "Location Sync", dynamic: false, permissions: ['inventory:location:view'] },
  { route: '/app/location/locations', label: "Locations", dynamic: false, permissions: ['location:read'] },
  { route: '/app/location/locations/:id', label: "Locations", dynamic: true, permissions: ['location:read'] },
  { route: '/app/location/locations/:locationId/defaults', label: "Defaults", dynamic: true, permissions: ['location:read'] },
  { route: '/app/location/locations/new', label: "New", dynamic: false, permissions: ['location:write'] },
  { route: '/app/location/mobile-units', label: "Mobile Units", dynamic: false, permissions: ['location:mobile-unit:read'] },
  { route: '/app/location/storage-locations', label: "Storage Locations", dynamic: false, permissions: ['location:read'] },
  { route: '/app/order/:orderId/cancel', label: "Cancel", dynamic: true, permissions: ['order:order:cancel'] },
  { route: '/app/order/:orderId/price-override/:lineId', label: "Price Override", dynamic: true, permissions: ['order:price_override:view'] },
  { route: '/app/order/cart', label: "Cart", dynamic: false, permissions: ['order:order:create'] },
  { route: '/app/order/cart/:orderId', label: "Cart", dynamic: true, permissions: ['order:order:view'] },
  { route: '/app/people', label: "", dynamic: false },
  { route: '/app/people/bulk-import/people', label: "People", dynamic: false, permissions: ['bulkImport:upload:execute'] },
  { route: '/app/people/directory', label: "Directory", dynamic: false, permissions: ['people-contact:person:view'] },
  { route: '/app/people/employees/:id', label: "Employees", dynamic: true },
  { route: '/app/people/employees/:id/offboard', label: "Offboard", dynamic: true, permissions: ['people:employee:deactivate'] },
  { route: '/app/people/employees/new', label: "New", dynamic: false, permissions: ['people:employee:create'] },
  { route: '/app/people/identity-compliance', label: "Identity Compliance", dynamic: false, permissions: ['people:compliance:view'] },
  { route: '/app/people/person/:personId/locations', label: "Locations", dynamic: true, permissions: ['people:employee:view'] },
  { route: '/app/people/rbac/:personUuid', label: "Rbac", dynamic: true, permissions: ['people-contact:role:view'] },
  { route: '/app/people/timekeeping/approval', label: "Approval", dynamic: false, permissions: ['people:timekeeping:view'] },
  { route: '/app/people/timekeeping/discrepancy', label: "Discrepancy", dynamic: false, permissions: ['accounting:time:export'] },
  { route: '/app/people/timekeeping/export', label: "Export", dynamic: false, permissions: ['accounting:export:view'] },
  { route: '/app/people/timekeeping/work-session', label: "Work Session", dynamic: false },
  { route: '/app/people/timekeeping/work-session/:sessionId/submit', label: "Submit", dynamic: true },
  { route: '/app/platform/tenants', label: "Tenants", dynamic: false, roles: ['ROLE_PLATFORM_ADMIN'], permissions: ['platform:tenant:read'] },
  { route: '/app/platform/tenants/:id', label: "Tenants", dynamic: true, roles: ['ROLE_PLATFORM_ADMIN'], permissions: ['platform:tenant:read'] },
  { route: '/app/platform/tenants/new', label: "New", dynamic: false, roles: ['ROLE_PLATFORM_ADMIN'], permissions: ['platform:tenant:create'] },
  { route: '/app/positivity', label: "", dynamic: false, roles: ['ROLE_ADMIN'], permissions: ['supplier:profile:read'] },
  { route: '/app/positivity/exchanges', label: "Exchanges", dynamic: false, roles: ['ROLE_ADMIN'], permissions: ['supplier:audit:read'] },
  { route: '/app/positivity/exchanges/:exchangeId', label: "Exchanges", dynamic: true, roles: ['ROLE_ADMIN'], permissions: ['supplier:audit:read'] },
  { route: '/app/positivity/manual-review', label: "Manual Review", dynamic: false, roles: ['ROLE_ADMIN'], permissions: ['supplier:transmission:read'] },
  { route: '/app/positivity/profiles/:vendorProfileId', label: "Profiles", dynamic: true, roles: ['ROLE_ADMIN'], permissions: ['supplier:profile:read'] },
  { route: '/app/product', label: "", dynamic: false },
  { route: '/app/product/bulk-import/catalog', label: "Catalog", dynamic: false, permissions: ['bulkImport:upload:execute'] },
  { route: '/app/product/bulk-import/price', label: "Price", dynamic: false, permissions: ['bulkImport:upload:execute'] },
  { route: '/app/product/catalog', label: "Catalog", dynamic: false, permissions: ['catalog:product:view'] },
  { route: '/app/product/catalog/:productId', label: "Catalog", dynamic: true, permissions: ['catalog:product:view'] },
  { route: '/app/product/catalog/enrichment/review/:treadDesignId', label: "Review", dynamic: true, permissions: ['catalog:tread_design:view'] },
  { route: '/app/product/catalog/enrichment/unmatched', label: "Unmatched", dynamic: false, permissions: ['catalog:tread_design:view'] },
  { route: '/app/product/inventory/availability', label: "Availability", dynamic: false, permissions: ['inventory:availability:read'] },
  { route: '/app/product/inventory/feeds', label: "Feeds", dynamic: false },
  { route: '/app/product/location/locations-roster', label: "Locations Roster", dynamic: false, permissions: ['location:read'] },
  { route: '/app/product/pricing/location-overrides', label: "Location Overrides", dynamic: false, permissions: ['catalog:location_price_override:read'] },
  { route: '/app/product/pricing/msrp', label: "Msrp", dynamic: false, permissions: ['catalog:msrp:read'] },
  { route: '/app/product/pricing/price-books', label: "Price Books", dynamic: false, permissions: ['catalog:price_book:read'] },
  { route: '/app/security', label: "", dynamic: false, roles: ['ROLE_ADMIN'], permissions: ['security:role:view'] },
  { route: '/app/security/audit', label: "Audit", dynamic: false, roles: ['ROLE_ADMIN'], permissions: ['shop:schedule:view', 'appointments:view'] },
  { route: '/app/security/audit-logs', label: "Audit Logs", dynamic: false, roles: ['ROLE_ADMIN'], permissions: ['security:audit:view'] },
  { route: '/app/security/permissions', label: "Permissions", dynamic: false, roles: ['ROLE_ADMIN'], permissions: ['security:permission:view'] },
  { route: '/app/security/roles/:name', label: "Roles", dynamic: true, roles: ['ROLE_ADMIN'], permissions: ['security:role:view'] },
  { route: '/app/security/users/provision', label: "Provision", dynamic: false, roles: ['ROLE_ADMIN'], permissions: ['security:user:create'] },
  { route: '/app/shopmgmt', label: "", dynamic: false },
  { route: '/app/shopmgmt/appointments/:id/assignments', label: "Assignments", dynamic: true, permissions: ['appointments:view', 'shop:schedule:view'] },
  { route: '/app/shopmgmt/appointments/:id/dispatch-assign', label: "Dispatch Assign", dynamic: true, permissions: ['shop:bay:assign'] },
  { route: '/app/shopmgmt/appointments/:id/edit', label: "Edit", dynamic: true, permissions: ['appointments:view', 'shop:schedule:view'] },
  { route: '/app/shopmgmt/appointments/:id/override-conflict', label: "Override Conflict", dynamic: true, permissions: ['shop:schedule:edit', 'appointments:reschedule'] },
  { route: '/app/shopmgmt/appointments/:id/reschedule', label: "Reschedule", dynamic: true, permissions: ['appointments:reschedule'] },
  { route: '/app/shopmgmt/appointments/new', label: "New", dynamic: false, permissions: ['appointments:create', 'shop:schedule:edit'] },
  { route: '/app/shopmgmt/appointments/new/crm', label: "Crm", dynamic: false, permissions: ['appointments:create', 'shop:schedule:edit'] },
  { route: '/app/shopmgmt/dispatch-board', label: "Dispatch Board", dynamic: false, permissions: ['workorder:dashboard:view'] },
  { route: '/app/shopmgmt/mechanics/availability', label: "Availability", dynamic: false, permissions: ['people:availability:view'] },
  { route: '/app/shopmgmt/mechanics/roster', label: "Roster", dynamic: false, permissions: ['shop:technician:view'] },
  { route: '/app/shopmgmt/schedule', label: "Schedule", dynamic: false, permissions: ['shop:schedule:view'] },
  { route: '/app/shopmgmt/shop-dashboard', label: "Shop Dashboard", dynamic: false, permissions: ['workorder:dashboard:view'] },
  { route: '/app/sitemap', label: "", dynamic: false },
  { route: '/app/workexec', label: "", dynamic: false },
  { route: '/app/workexec/estimate-list', label: "Estimate List", dynamic: false, permissions: ['workorder:estimate:view'] },
  { route: '/app/workexec/estimates/:estimateId', label: "Estimates", dynamic: true, permissions: ['workorder:estimate:view'] },
  { route: '/app/workexec/estimates/:estimateId/approval/:approvalId', label: "Approval", dynamic: true, permissions: ['workorder:estimate:view'] },
  { route: '/app/workexec/estimates/:estimateId/approval/digital', label: "Digital", dynamic: true, permissions: ['workorder:estimate:approve'] },
  { route: '/app/workexec/estimates/:estimateId/approval/in-person', label: "In Person", dynamic: true, permissions: ['workorder:estimate:approve'] },
  { route: '/app/workexec/estimates/:estimateId/approval/partial', label: "Partial", dynamic: true, permissions: ['workorder:estimate:approve'] },
  { route: '/app/workexec/estimates/:estimateId/approval/submit', label: "Submit", dynamic: true, permissions: ['workorder:estimate:submit'] },
  { route: '/app/workexec/estimates/:estimateId/labor', label: "Labor", dynamic: true, permissions: ['workorder:estimate:view'] },
  { route: '/app/workexec/estimates/:estimateId/parts', label: "Parts", dynamic: true, permissions: ['workorder:estimate:view'] },
  { route: '/app/workexec/estimates/:estimateId/revise', label: "Revise", dynamic: true, permissions: ['workorder:estimate:reopen'] },
  { route: '/app/workexec/estimates/:estimateId/summary', label: "Summary", dynamic: true, permissions: ['workorder:estimate:view'] },
  { route: '/app/workexec/estimates/new', label: "New", dynamic: false, permissions: ['workorder:estimate:create'] },
  { route: '/app/workexec/timer', label: "Timer", dynamic: false, permissions: ['workorder:labor:view'] },
  { route: '/app/workexec/travel-time', label: "Travel Time", dynamic: false, permissions: ['workorder:labor:add'] },
  { route: '/app/workexec/wip-status', label: "Wip Status", dynamic: false, permissions: ['workorder:wip:view'] },
  { route: '/app/workexec/workorders/:id/operational-context', label: "Operational Context", dynamic: true },
  { route: '/app/workexec/workorders/:workorderId', label: "Workorders", dynamic: true },
  { route: '/app/workexec/workorders/:workorderId/assign', label: "Assign", dynamic: true, permissions: ['workorder:workorder:assign-technician'] },
  { route: '/app/workexec/workorders/:workorderId/change-requests', label: "Change Requests", dynamic: true, permissions: ['workorder:change_request:view'] },
  { route: '/app/workexec/workorders/:workorderId/finalize', label: "Finalize", dynamic: true, permissions: ['workorder:workorder:view'] },
  { route: '/app/workexec/workorders/:workorderId/invoice-finalization', label: "Invoice Finalization", dynamic: true },
  { route: '/app/workexec/workorders/:workorderId/labor', label: "Labor", dynamic: true, permissions: ['workorder:labor:view'] },
  { route: '/app/workexec/workorders/:workorderId/parts', label: "Parts", dynamic: true, permissions: ['workorder:parts:view'] },
  { route: '/app/workexec/workorders/from-appointment', label: "From Appointment", dynamic: false, permissions: ['workorder:estimate:create'] },
];
